config/routes.rb
Rails.application.routes.draw do

  # Devise setup
  devise_for :doctors, except: [:show], path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}, :controllers => { registrations: 'registrations' }
  
  # Landing Page / Root route
  get '/', to: 'landing_page#view', as: :root_path

  authenticate :doctor do
    
    # Auditor setup
    mount Auditor::Engine, at: '/', as: 'auditor'

    # Medical Facility routes
    resources :medical_facility, only: [:index, :create, :edit, :update, :show, :destroy], path: '/facilities' do
    	get :remove_facility_head
    	post :assign_facility_head
    	post :search_doctors

      resources :department, only: [:create, :show] do
        get :remove_department_head
        post :assign_department_head
        post :hire

        resources :referrals, only: [:create]

        resources :doctors, only: [] do
          get :fire
        end
      end
    end

    # Doctor routes
    resources :doctors, only: [:index, :show]

    # Patient routes
    resources :patients, only: [:index, :show, :create, :update] do
      patch :assign_doctor
      post :create_appointment
      post :create_appointment_from_referral

      resources :patient_records, only: [:create] do
        patch :archive_record
      end

      resources :appointments, only: [] do
        get :cancel_appointment
      end
    end

  end
end

app/models/department.rb
class Department < ApplicationRecord
	validates :name, presence: true
  	belongs_to :medical_facility, required: true
  	belongs_to :department_head, :class_name => 'Doctor', :foreign_key => 'department_head_id', optional: true
  	has_many :employees, :class_name => 'Doctor', :foreign_key => 'workplace_id'
  	has_many :referrals
end

app/controllers/department_controller.rb
class DepartmentController < ApplicationController
	before_action :authenticate_doctor!
	
	def create
		@current_facility = MedicalFacility.find(params[:medical_facility_id])
		begin
			@current_facility.departments.create(department_params)
			@current_facility.save!()
			flash[:success] = 'New department created'
		rescue => ex
			flash[:danger] = 'Failed to create new department'
		end
		
		Auditor::AuditRecord.create(entry: "#{current_doctor.full_name} created a new department in #{@current_facility.name}: #{department_params[:name]}.", subject: "DepartmentCreated", author: current_doctor.full_name)

		redirect_back(fallback_location: :root_path)
	end

	def show
		@current_facility = MedicalFacility.find(params[:medical_facility_id])
		@current_department = @current_facility.departments.find(params[:id])
	end

	def hire
		@current_facility = MedicalFacility.find(params[:medical_facility_id])
		@current_department = @current_facility.departments.find(params[:department_id])
		@hired_doctor = Doctor.find(params[:doctor][:doctor_id])

		@current_department.employees << @hired_doctor

		Auditor::AuditRecord.create(entry: "#{current_doctor.full_name} hired #{@hired_doctor.full_name} to #{@current_department.medical_facility.name.possessive} #{@current_department.name}.", subject: "DepartmentUpdate", author: current_doctor.full_name)

		flash[:success] = "Successfully hired #{@hired_doctor.full_name}!"
		redirect_back(fallback_location: :root_path)
	end

	# Removes the head of the department
	def remove_department_head
		@current_facility = MedicalFacility.find(params[:medical_facility_id])
		@current_department = @current_facility.departments.find(params[:department_id])
		redirect_to "/403.html" and return false unless current_doctor.can_edit_department?(@current_department)

		old_department_head_name = @current_department.department_head.full_name
		@current_department.update_attribute(:department_head, nil)
		@current_department.save!

		Auditor::AuditRecord.create(entry: "#{current_doctor.full_name} removed #{old_department_head_name} as the head of #{@current_department.medical_facility.name.possessive} #{@current_department.name}.", subject: "DepartmentUpdate", author: current_doctor.full_name)

		flash[:success] = 'Successfully removed department head'
		redirect_back(fallback_location: :root_path)
	end

	# Assigns the head of the department
	def assign_department_head
		@current_facility = MedicalFacility.find(params[:medical_facility_id])
		@current_department = @current_facility.departments.find(params[:department_id])
		redirect_to "/403.html" and return false unless current_doctor.can_edit_department?(@current_department)
		redirect_to "/422.html" and return false unless params[:doctor_id] != nil

		head = Doctor.find(params[:doctor_id])

		@current_department.update_attribute(:department_head, head)
		@current_department.save!

		Auditor::AuditRecord.create(entry: "#{current_doctor.full_name} assigned #{head.full_name} as the head of #{@current_department.medical_facility.name.possessive} #{@current_department.name}.", subject: "DepartmentUpdate", author: current_doctor.full_name)

		flash[:success] = 'Successfully assigned new department head'
		redirect_back(fallback_location: :root_path)
	end

	private 

	def department_params
		params.require(:department).permit(:name, :medical_facility_id)
	end
end

app/helpers/department_helper.rb
module DepartmentHelper
end

app/views/department/_create_referral_modal.html.erb
<div class="modal fade" id="createReferralModal" tabindex="-1" role="dialog" aria-labelledby="createReferralModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" >Create Referral</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= bootstrap_form_with(model: Referral.new, url: medical_facility_department_referrals_path(@current_facility.id, @current_department.id), local: true) do |f| %>
          <%= f.collection_select(:patient_id, current_doctor.patients.all, :id, :full_name) %>
          <%= f.text_field :reason %>
      </div>
      <div class="modal-footer">
      	<%= f.submit "Create", :class => "btn btn-superuser" %>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    		<% end %>
      </div>
    </div>
  </div>
</div>

app/views/department/_doctor_card.html.erb
<div class="card mb-2 doctor-card">
  <div class="card-body">
    <h5 class="card-title"><%= doctor.full_name %></h5>

	<% if current_doctor.can_edit_department?(@current_department) %>
		<div class="btn-group justify-content-between btn-block" role="group">
		    <a class="btn btn-block btn-primary" href="<%= doctor_path(doctor.id) %>">Show</a>
		    <a class="btn btn-superuser" href="<%= medical_facility_department_doctor_fire_path(@current_facility.id, @current_department.id, doctor.id) %>">Fire Doctor</a>
	    </div>
    <% else %>
		<a class="btn btn-block btn-primary" href="<%= doctor_path(doctor.id) %>">Show</a>
  	<% end %>

  </div>
</div>

app/views/department/_doctor_hire_modal.html.erb
<div class="modal fade" id="hireDoctorModal" tabindex="-1" role="dialog" aria-labelledby="hireDoctorModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" >Hire Doctor</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= bootstrap_form_with(model: Doctor.new, url: medical_facility_department_hire_path(@current_facility.id, @current_department.id), local: true) do |f| %>
          <%= f.collection_select(:doctor_id, Doctor.all, :id, :full_name) %>
      </div>
      <div class="modal-footer">
          <%= f.submit "Save", :class => "btn btn-superuser" %>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    		<% end %>
      </div>
    </div>
  </div>
</div>

app/views/department/_referral_card.html.erb
<div class="card mb-2 referral-card">
  <div class="card-body">
    
	<h5 class="card-title"><%= referral.patient.full_name %></h5>
	<p class="mb-0">
		<strong>Referred by: </strong> <%= referral.doctor.full_name %>
		<br>
		<strong>Reason:</strong> <%= referral.reason %>
	</p>

	<% if referral.department.employees.include?(current_doctor) %>
		<button class="btn btn-sm btn-superuser mt-3" type="submit" data-toggle="modal" data-target="#refferedAppointmentModal-<%= referral.id %>">Create Appointment</button>

		<%= render partial:"referred_appointment_modal", locals: {referral: referral} %>
	<% end %>

	<a class="btn btn-primary btn-sm mt-3" href="<%= patient_path(referral.patient.id) %>">View Patient</a>

  </div>
</div>

app/views/department/_referred_appointment_modal.html.erb
<div class="modal fade" id="refferedAppointmentModal-<%= referral.id %>" tabindex="-1" role="dialog" aria-labelledby="refferedAppointmentModal-<%= referral.id %>" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" >Create Referred Appointment</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= bootstrap_form_with(model: Appointment.new, url:patient_create_appointment_from_referral_path(referral.patient.id), local: true) do |f| %>
          <%= f.text_field :patient, :value => referral.patient.full_name, :readonly => true %>
          <%= f.text_field :reason, :value => referral.reason, :readonly => true %>
          <%= f.hidden_field(:referral_id, :value => referral.id) %>
          <%= f.datetime_field :scheduled %>
      </div>
      <div class="modal-footer">
        <%= f.submit "Add Record", :class => "btn btn-superuser" %>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/department/show.html.erb
<div class="row">
	<div class="col">
		<h1><%= @current_department.name %></h1>
		<h4><%= @current_facility.name %></h4>
	</div>
</div>

<div class="row">

	<div class="col-md-12 col-lg-8 mb-3">

		<!-- Referrals List -->
		<div class="card">
			<div class="card-body">
				<h5>Referrals</h5>

				<ul class="list-group list-group-flush">
					<% if @current_department.referrals.count == 0 %>
						<strong>No Referrals</strong>
					<% else %>
						<% @current_department.referrals.order('referrals.created_at DESC').each do |referral| %>
							<%= render partial:"referral_card", locals:{referral: referral} %>
						<% end %>
					<% end %>
				</ul>

				<button class="btn btn-primary" type="submit" data-toggle="modal" data-target="#createReferralModal">Create Referral</button>
				<a class="btn btn-secondary" href="<%= medical_facility_path(@current_facility.id) %>">Back to <%= @current_facility.name %></a>
			</div>
		</div>
	</div>

	<div class="col-md-12 col-lg-4 mb-3">

		<!-- Department Head -->
		<div class="card">
			<div class="card-body">
				<h5>Head of <%= @current_department.name %></h5>
				<strong>
					<% if @current_department.department_head_id? %>
						<%= @current_department.department_head.full_name %>
					<% else %>
						No Department Head Assigned
					<% end %>
				</strong>

				<div class="mt-3 mb=3">
				<% if @current_department.department_head_id %>
					<%= link_to "Show", doctor_path(@current_department.department_head_id), :class => "btn btn-primary" %>
				<% end %>

				<% if current_doctor.can_edit_department?(@current_department) %>
					<% if @current_department.department_head_id? %>
						<button class="btn btn-superuser type="submit" data-toggle="modal" data-target="#doctorSearchModal">Reassign</button>
						<%= link_to "Remove", medical_facility_department_remove_department_head_path(@current_facility.id, @current_department.id), :class => "btn btn-superuser" %>
					<% else %>
						<button class="btn btn-superuser" type="submit" data-toggle="modal" data-target="#doctorSearchModal">Assign</button>
					<% end %>
				<% end %>
				</div>
			</div>
		</div>

		<!-- Doctor List -->
		<div class="card mt-3">
			<div class="card-body">
				<h5>Doctors</h5>
				<!-- Superuser Controls for hiring new Doctor -->
				<% if current_doctor.superuser? %>
					<button class="btn btn-sm btn-block btn-superuser mb-3" type="submit" data-toggle="modal" data-target="#hireDoctorModal">Hire Doctor</button>
				<% end %>

				<!-- Search -->
				<div class="input-group mb-3">
					<div class="input-group-prepend">
						<span class="input-group-text" style="color: #ff000;">Search</span>
					</div>
					<input type="text" id="doctor-hire-searchbox" class="form-control" placeholder="Name or Address..." onkeyup="doctorHireSearch()">
				</div>

				<ul class="list-group list-group-flush">
					<% @current_department.employees.all.each do |doctor| %>
						<%= render partial: "doctor_card", locals: {doctor: doctor} %>
					<% end %>
				</ul>
			</div>
		</div>

	</div>

</div>

<%= render partial: "doctor_search", locals: {superuser_action: true, modal_title: "Assign Head of #{@current_department.name}", primary_action_text: "Assign", primary_action_path: medical_facility_department_assign_department_head_path(@current_facility.id, @current_department.id), primary_action_method: "post"} %>

<%= render partial: "doctor_hire_modal", locals: {department: @current_department} %>
<%= render partial: "create_referral_modal" %>

<%= javascript_include_tag "department_show" %>