config/routes.rb
Rails.application.routes.draw do

  # Devise setup
  devise_for :doctors, except: [:show], path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}, :controllers => { registrations: 'registrations' }
  
  # Landing Page / Root route
  get '/', to: 'landing_page#view', as: :root_path

  authenticate :doctor do
    
    # Auditor setup
    mount Auditor::Engine, at: '/', as: 'auditor'

    # Medical Facility routes
    resources :medical_facility, only: [:index, :create, :edit, :update, :show, :destroy], path: '/facilities' do
    	get :remove_facility_head
    	post :assign_facility_head
    	post :search_doctors

      resources :department, only: [:create, :show] do
        get :remove_department_head
        post :assign_department_head
        post :hire

        resources :referrals, only: [:create]

        resources :doctors, only: [] do
          get :fire
        end
      end
    end

    # Doctor routes
    resources :doctors, only: [:index, :show]

    # Patient routes
    resources :patients, only: [:index, :show, :create, :update] do
      patch :assign_doctor
      post :create_appointment
      post :create_appointment_from_referral

      resources :patient_records, only: [:create] do
        patch :archive_record
      end

      resources :appointments, only: [] do
        get :cancel_appointment
      end
    end

  end
end

app/models/medical_facility.rb
class MedicalFacility < ApplicationRecord
	validates :name, presence: true
	validates :address, presence: true
	validates :description, presence: true
	validates :latitude, presence: true
	validates :longitude, presence: true
	validates :facility_type, presence: true

	belongs_to :facility_head, :class_name => 'Doctor', :foreign_key => 'facility_head_id', optional: true
	has_many :departments
	has_many :employees, through: :departments
end

app/controllers/medical_facility_controller.rb
class MedicalFacilityController < ApplicationController
	before_action :authenticate_doctor!

	def index
		@deleted_facility_name = params[:last_deleted_facility]
		@medical_facilities = MedicalFacility.select('id, name, address, description, latitude, longitude, facility_type').all;
	end

	def create
		redirect_to "/403.html" and return false unless current_doctor.superuser?

		@new_facility = MedicalFacility.new(medical_facility_params)
		@save_successful = @new_facility.save()

		Auditor::AuditRecord.create(entry: "#{current_doctor.full_name} created a new facility: #{@new_facility.name}.", subject: "FacilityCreated", author: current_doctor.full_name)
	end

	def edit
		@current_facility = MedicalFacility.find(params[:id])
		redirect_to "/403.html" and return false unless current_doctor.can_edit_facility?(@current_facility)
	end

	def update
		@current_facility = MedicalFacility.find(params[:id])
		redirect_to "/403.html" and return false unless current_doctor.can_edit_facility?(@current_facility)

		old_name = @current_facility.name
		old_facility_type = @current_facility.facility_type
		old_address = @current_facility.address
		old_description = @current_facility.description

		if @current_facility.update_attributes(medical_facility_params)

			Auditor::AuditRecord.create(entry: "#{current_doctor.full_name} updated facility: #{@current_facility.name}. Name: (#{old_name} -> #{@current_facility.name}) | Facility Type: (#{old_facility_type} -> #{@current_facility.facility_type}) | Address: (#{old_address} -> #{@current_facility.address}) | Description: (#{old_description} -> #{@current_facility.description})", subject: "FacilityUpdate", author: current_doctor.full_name)

			redirect_to url_for(@current_facility)
		else
			redirect_to "/500.html" and return false
		end
	end

	def show
		@current_facility = MedicalFacility.find(params[:id])
		redirect_to "/403.html" and return false unless current_doctor.can_view_facility?(@current_facility)

		@departments = @current_facility.departments
	end

	def destroy
		redirect_to "/403.html" and return false unless current_doctor.superuser?

		@deleted_facility = MedicalFacility.find(params[:id])
		deleted_facility_name = @deleted_facility.name
		@deleted_facility.delete

		Auditor::AuditRecord.create(entry: "#{current_doctor.full_name} destroyed #{deleted_facility_name}.", subject: "FacilityDestroyed", author: current_doctor.full_name)

		redirect_to medical_facility_index_path(last_deleted_facility: @deleted_facility.name)
	end

	# Removes the head of the facility
	def remove_facility_head
		@current_facility = MedicalFacility.find(params[:medical_facility_id])
		redirect_to "/403.html" and return false unless current_doctor.can_edit_facility?(@current_facility)

		old_facility_head_name = @current_facility.facility_head.full_name
		@current_facility.update_attribute(:facility_head, nil)
		@current_facility.save!

		Auditor::AuditRecord.create(entry: "#{current_doctor.full_name} removed #{old_facility_head_name} as the head of #{@current_facility.name}.", subject: "FacilityUpdate", author: current_doctor.full_name)

		flash[:success] = 'Successfully removed facility head'
		redirect_back(fallback_location: :root_path)
	end

	# Assigns the head of the facility
	def assign_facility_head
		@current_facility = MedicalFacility.find(params[:medical_facility_id])
		redirect_to "/403.html" and return false unless current_doctor.can_edit_facility?(@current_facility)
		redirect_to "/422.html" and return false unless params[:doctor_id] != nil

		@current_facility = MedicalFacility.find(params[:medical_facility_id])
		head = Doctor.find(params[:doctor_id])
		@current_facility.update_attribute(:facility_head, head)
		@current_facility.save!

		Auditor::AuditRecord.create(entry: "#{current_doctor.full_name} assigned #{head.full_name} as the head of #{@current_facility.name}.", subject: "FacilityUpdate", author: current_doctor.full_name)

		flash[:success] = 'Successfully assigned new facility head'
		redirect_back(fallback_location: :root_path)
	end

	# POST search for Doctors by name or email.
	# Used for AJAX calls
	def search_doctors
		@current_facility = MedicalFacility.find(params[:medical_facility_id])
		redirect_to "/403.html" and return false unless current_doctor.can_view_facility?(@current_facility)
		
		doctors = Doctor.where("first_name ILIKE :query OR last_name ILIKE :query OR email ILIKE :query", query: "%#{params[:query]}%").order(:first_name)

		render json: {:doctors => doctors}
	end

	def get_departments
		@current_facility = MedicalFacility.find(params[:medical_facility_id])
		redirect_to "/403.html" and return false unless current_doctor.can_view_facility?(@current_facility)

		departments = @current_facility.departments.all

		render json: {:departments => departments}
	end

	private

	def medical_facility_params
		params.require(:medical_facility).permit(:name, :address, :description, :facility_type, :latitude, :longitude)
	end
end

app/helpers/medical_facility_helper.rb
module MedicalFacilityHelper
end

app/views/medical_facility/_create_department_modal.html.erb
<div class="modal fade" id="createDepartmentModal" tabindex="-1" role="dialog" aria-labelledby="createDepartmentModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" >Create New Department</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= bootstrap_form_with(model: Department.new, url: medical_facility_department_index_path(@current_facility.id), validate: true, local: true) do |f| %>
    			<%= f.text_field :name %>
      </div>
      <div class="modal-footer">
      	<%= f.submit "Save", :class => "btn btn-superuser" %>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    		<% end %>
      </div>
    </div>
  </div>
</div>

app/views/medical_facility/_create_facility_modal.html.erb
<div class="modal fade" id="createFacilityModal" tabindex="-1" role="dialog" aria-labelledby="createFacilityModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" >Create New Facility</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= bootstrap_form_with(model: MedicalFacility.new, url: medical_facility_index_path, local: true, validate: true) do |f| %>
			<%= f.text_field :name %>
			<%= f.text_field :address %>
			<%= f.text_field :description %>
			<%= f.text_field :facility_type %>
			<%= f.number_field :latitude, step:0.000001 %>
			<%= f.number_field :longitude, step:0.000001 %>
      </div>
      <div class="modal-footer">
      	<%= f.submit "Save", :class => "btn btn-superuser" %>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
		<% end %>
      </div>
    </div>
  </div>
</div>

app/views/medical_facility/_delete_modal.html.erb
<div class="modal fade" id="deleteFacilityModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Delete <strong class="facility-details-name"></strong></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Really delete <strong class="facility-details-name">name_here</strong>?</p>
        <p>This action <strong>CAN NOT</strong> be reversed!</p>
      </div>
      <div class="modal-footer">
      	<a data-method="delete" class="btn btn-superuser medical-facility-btn-destroy">Confirm Deletion</a>
      	<button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel Delete</button>
      </div>
    </div>
  </div>
</div>

app/views/medical_facility/_department_card.html.erb
<div class="card mb-2 department-card">
  <div class="card-body">
    <h5 class="card-title"><%= department.name %></h5>

    <% if department.department_head_id? %>
    	<p class="card-text"><strong>Head: </strong><%= department.department_head.full_name %></p>
	<% else %>
		<p class="card-text"><strong>Head: </strong>None Assigned</p>
	<% end %>

	<a class="btn btn-block btn-primary" href="<%= medical_facility_department_path(@current_facility.id, department.id) %>">View</a>
  </div>
</div>

app/views/medical_facility/_doctor_card.html.erb
<div class="card mb-2 medical-facility-card">
  <div class="card-body">
    <h5 class="card-title"><%= doctor.full_name %></h5>
    <p class="card-text"><%= doctor.workplace.name %></p>

	<a class="btn btn-block btn-primary" href="<%= doctor_path(doctor.id) %>">Show</a>
  </div>
</div>

app/views/medical_facility/_facility_card.html.erb
<div class="card mb-2 medical-facility-card">
  <div class="card-body">
    <h5 class="card-title"><%= facility.name %></h5>
    <p class="card-text"><strong>Address: </strong> <%= facility.address %><br><strong>Type: </strong> <%= facility.facility_type %></p>

    <div class="btn-group justify-content-between btn-block" role="group">
	    <button class="btn btn-block btn-secondary" onclick="selectFacility(getFacilityByDbId(<%= facility.id %>))">View</button>
	    <a class="btn btn-primary" href=<%= medical_facility_path(facility.id) %>>More Details</a>
    </div>
  </div>
</div>

app/views/medical_facility/create.html.erb
<h1>New Medical Facility</h1>

<% if @save_successful %>
	<h2>Save Successful</h2>

	<strong>Name</strong>
	<p>
		<%= @new_facility.name %>
	</p>

	<strong>Address</strong>
	<p>
		<%= @new_facility.address %>
	</p>

	<strong>Description</strong>
	<p>
		<%= @new_facility.description %>
	</p>

	<strong>Latitude</strong>
	<p>
		<%= @new_facility.latitude %>
	</p>

	<strong>Longitude</strong>
	<p>
		<%= @new_facility.longitude %>
	</p>

	<a class="btn btn-primary" href="/facilities/<%= @new_facility.id %>">Show New Facility</a>
	<a class="btn btn-secondary" href="/facilities/<%= @new_facility.id %>/edit">Edit</a>

<% else %>
	<h2>Save Failed</h2>
	<% if @current_doctor.superuser? %>
		<strong>Please check application logs.</strong>
	<% else %>
		<strong>Please notify the website administrator.</strong>
	<% end %>
	<br>
<% end %>

<a class="btn btn-secondary" href="/facilities">Go Back</a>

app/views/medical_facility/edit.html.erb
<h1><%= @current_facility.name %></h1>
<h2>Edit Mode</h2>

<%= bootstrap_form_with(model: @current_facility, url: url_for(@current_facility), validate: true, local: true) do |f| %>
	<%= f.text_field :name %>
	<%= f.text_field :address %>
	<%= f.text_field :description %>
	<%= f.text_field :facility_type %>
	<%= f.number_field :latitude, step:0.000001 %>
	<%= f.number_field :longitude, step:0.000001 %>
	<%= f.submit "Save Changes", :class => "btn btn-primary" %>

	<a class="btn btn-secondary" href="/facilities/<%= @current_facility.id %>">Show</a>
	<a class="btn btn-secondary" href="/facilities">All Facilities</a>
<% end %>

app/views/medical_facility/index.html.erb
<div class="row">
	<div class="col">
		<h1>Medical Facilities</h1>

		<% unless @deleted_facility_name.nil? %>
			<div class="alert alert-deleted alert-dismissable">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<strong>Successfully Deleted Facility</strong> <%= @deleted_facility_name %>
			</div>
		<% end %>
	</div>
</div>

<div class="row">

	<div class="col-md-12 col-lg-8 mb-3">
		<!-- Map -->
		<div id="map-container" class="z-depth-1" style="height: 350px"></div>

		<!-- Facility Details -->
		<div class="card border-flat-top border-no-top">
			<div class="card-body">
				<h3 class="facility-details-name">Please Select a Facility</h3>
				<span class="medical-facility-selection">
					<p class="facility-details-address">address_goes_here</p>
					<strong>Description</strong><p class="facility-details-description">description_goes_here</p>

					<a class="btn btn-primary medical-facility-btn-view" href="#">More Details</a>
				</span>

				<!-- Superuser Controls for currently selected Facility -->
				<% if current_doctor.superuser? %>
					<a class="btn btn-superuser medical-facility-selection medical-facility-btn-edit">Edit</a>
					<button class="btn btn-superuser medical-facility-selection" data-toggle="modal" data-target="#deleteFacilityModal">Delete</button>
				<% end %>
			</div>
		</div>
	</div>
	
	<!-- Facility List -->
	<div class="col-md-12 col-lg-4">
		<div class="card">
			<div class="card-body">

				<!-- Superuser Controls for creating new Facility -->
				<% if current_doctor.superuser? %>
					<button class="btn btn-sm btn-block btn-superuser mb-3" type="submit" data-toggle="modal" data-target="#createFacilityModal">Create New Facility</button>
				<% end %>

				<!-- Search -->
				<div class="input-group mb-3">
					<div class="input-group-prepend">
						<span class="input-group-text" style="color: #ff000;">Search</span>
					</div>
					<input type="text" id="medical-facility-searchbox" class="form-control" placeholder="Name or Address..." onkeyup="facilitySearch()">
				</div>

				<ul class="list-group list-group-flush">
				<% @medical_facilities.each do |facility| %>
					<%= render partial: "facility_card", locals: {facility: facility} %>
				<% end %>
				<% if @medical_facilities.empty? %>
					No medical facilities have been created yet.
				<% end %>
				</ul>
			</div>
		</div>
	</div>

	<!--########-->
	<!-- Modals -->
	<!--########-->

	<!-- Create Factory Modal -->
	<%= render partial: "create_facility_modal" %>

	<!-- Delete Factory Modal -->
	<%= render partial: "delete_modal" %>

</div>

<script>
	// Hack to get Ruby variables in Javascript files
	medical_facilities = <%= @medical_facilities.to_json.html_safe %>;
</script>
<%= javascript_include_tag "medical_facility_index" %>

app/views/medical_facility/show.html.erb
<div class="row">
	<div class="col">
		<h1><%= @current_facility.name %></h1>
	</div>
</div>

<div class="row">
	<div class="col-md-12 col-lg-8 mb-3">

		<!-- Map -->
		<div id="map-container" class="z-depth-1" style="height: 350px"></div>

		<div class="card border-flat-top border-no-top">
			<div class="card-body">
				<h3><%= @current_facility.name %></h3>
				<p><%= @current_facility.address %></p>
				<strong class="mt-3">Description</strong>
				<p><%= @current_facility.description %></p>

				<a class="btn btn-secondary" href="/facilities">All Facilities</a>

				<!-- Superuser Controls for currently selected Facility -->
				<% if current_doctor.can_edit_facility?(@current_facility) %>
					<%= link_to "Edit", edit_medical_facility_path, :class => "btn btn-superuser" %>
					<% if current_doctor.superuser? %>
						<button class="btn btn-superuser" data-toggle="modal" data-target="#deleteFacilityModal">Delete</button>
					<% end %>
				<% end %>
			</div>
		</div>
	</div>

	<div class="col-md-12 col-lg-4">

		<!-- Hospital Head -->
		<div class="card">
			<div class="card-body">
				<h5>Head of <%= @current_facility.name %></h5>
				<strong>
					<% if @current_facility.facility_head_id? %>
						<%= @current_facility.facility_head.full_name %>
					<% else %>
						No Facility Head Assigned
					<% end %>
				</strong>

				<div class="mt-3 mb=3">
				<% if @current_facility.facility_head_id %>
					<%= link_to "Show", doctor_path(@current_facility.facility_head_id), :class => "btn btn-primary" %>
				<% end %>

				<% if current_doctor.can_edit_facility?(@current_facility) %>
					<% if @current_facility.facility_head_id? %>
						<button class="btn btn-superuser type="submit" data-toggle="modal" data-target="#doctorSearchModal">Reassign</button>
						<%= link_to "Remove", medical_facility_remove_facility_head_path(@current_facility.id), :class => "btn btn-superuser" %>
					<% else %>
						<button class="btn btn-sm btn-block btn-superuser type="submit" data-toggle="modal" data-target="#doctorSearchModal">Assign</button>
					<% end %>
				<% end %>
				</div>
			</div>
		</div>

		<!-- Tab Header -->
		<ul id="facility_tabs" class="nav nav-pills mt-3" role="tablist">
		  <li class="nav-item">
		    <a class="nav-link active" id="departments-tab" data-toggle="tab" role="tab" aria-controls="departments" href="#departments" aria-selected="true">Departments</a>
		  </li>
		  <li class="nav-item">
		    <a class="nav-link" id="doctors-tab" data-toggle="tab" role="tab"  aria-controls="doctors" href="#doctors" aria-selected="false">Doctors</a>
		  </li>
		</ul>

		<!-- Tab Content -->
		<div class="tab-content">

			<!-- Departments -->
			<div class="tab-pane active" id="departments" role="tabpanel" aria-labelledby="departments-tab">
				<div class="card border-flat-top-left">
					<div class="card-body">
						<!-- Superuser/Admin Controls for creating new Department -->
						<% if current_doctor.can_edit_facility?(@current_facility) %>
							<button class="btn btn-sm btn-block btn-superuser" type="submit" data-toggle="modal" data-target="#createDepartmentModal">Create New Department</button>
						<% end %>

						<!-- Department Search -->
						<div class="input-group mt-3 mb-3">
							<div class="input-group-prepend">
								<span class="input-group-text" style="color: #ff000;">Search</span>
							</div>
							<input type="text" id="department-searchbox" class="form-control" placeholder="Department Name or Head..." onkeyup="departmentSearch()">
						</div>

						<!-- Department List -->
						<ul class="list-group list-group-flush">
							<% @departments.each do |department| %>
								<%= render partial: "department_card", locals: {department: department} %>
							<% end %>
						</ul>
					</div>
				</div>
			</div>

			<!-- Doctors -->
			<div class="tab-pane" id="doctors" role="tabpanel" aria-labelledby="doctors-tab">
				<div class="card border-flat-top-left">
					<div class="card-body">

						<!-- Doctor Search -->
						<div class="input-group mb-3">
							<div class="input-group-prepend">
								<span class="input-group-text" style="color: #ff000;">Search</span>
							</div>
							<input type="text" id="medical-facility-searchbox" class="form-control" placeholder="Name or Department..." onkeyup="facilitySearch()">
						</div>

						<!-- Doctor List -->
						<ul class="list-group list-group-flush">
							<% @current_facility.employees.all.each do |doctor| %>
								<%= render partial: "doctor_card", locals: {doctor: doctor} %>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<%= render partial: "doctor_search", locals: {superuser_action: true, modal_title: "Assign Head of #{@current_facility.name}", primary_action_text: "Assign", primary_action_path: medical_facility_assign_facility_head_path(@current_facility.id), primary_action_method: "post"} %>

<!-- Modals -->
<%= render partial: "create_department_modal" %>
<%= render partial: "delete_modal" %>

<script>
	// Hack to get Ruby variables in Javascript files
	medical_facility = <%= @current_facility.to_json.html_safe %>;
	departments = <%= @departments.to_json.html_safe %>;
	start_location_lat = <%= @current_facility.latitude.to_json.html_safe %>;
	start_location_lng = <%= @current_facility.longitude.to_json.html_safe %>;
</script>
<%= javascript_include_tag "medical_facility_show" %>