config/routes.rb
Rails.application.routes.draw do

  # Devise setup
  devise_for :doctors, except: [:show], path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}, :controllers => { registrations: 'registrations' }
  
  # Landing Page / Root route
  get '/', to: 'landing_page#view', as: :root_path

  authenticate :doctor do
    
    # Auditor setup
    mount Auditor::Engine, at: '/', as: 'auditor'

    # Medical Facility routes
    resources :medical_facility, only: [:index, :create, :edit, :update, :show, :destroy], path: '/facilities' do
    	get :remove_facility_head
    	post :assign_facility_head
    	post :search_doctors

      resources :department, only: [:create, :show] do
        get :remove_department_head
        post :assign_department_head
        post :hire

        resources :referrals, only: [:create]

        resources :doctors, only: [] do
          get :fire
        end
      end
    end

    # Doctor routes
    resources :doctors, only: [:index, :show]

    # Patient routes
    resources :patients, only: [:index, :show, :create, :update] do
      patch :assign_doctor
      post :create_appointment
      post :create_appointment_from_referral

      resources :patient_records, only: [:create] do
        patch :archive_record
      end

      resources :appointments, only: [] do
        get :cancel_appointment
      end
    end

  end
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :owned_facilities, :class_name => "MedicalFacility", :foreign_key => "facility_head_id"
  has_many :owned_departments, :class_name => "Department", :foreign_key => "department_head_id"
  has_many :patients
  has_many :patient_records
  has_many :appointments
  has_many :referrals
  belongs_to :workplace, :class_name => "Department", :foreign_key => "workplace_id", optional: true

  def full_name
  	return first_name + " " + last_name
  end

  def can_edit_facility?(medical_facility)
    return true if superuser?
    return true if medical_facility.facility_head_id == id
    return false
  end

  def can_view_facility?(medical_facility)
    # TODO: Add view check here
    return true
    return can_edit_facility?(medical_facility)
  end

  def can_edit_department?(department)
    return true if can_edit_facility?(department.medical_facility)
    return true if department.department_head_id == id
    return false
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
	before_action :authenticate_doctor!

	def index
		@doctors = Doctor.all
	end

	def show
		@this_doctor = Doctor.find(params[:id])
	end

	def fire
		begin
			@current_facility = MedicalFacility.find(params[:medical_facility_id])
			@current_department = @current_facility.departments.find(params[:department_id])
			@fired_doctor = @current_department.employees.find(params[:doctor_id])
			redirect_to "/403.html" and return false unless current_doctor.can_edit_department?(@current_department)

			@fired_doctor.update_attribute(:workplace, nil)
		rescue Exception => e
			flash[:danger] = 'Failed to fire employee.'
			redirect_back(fallback_location: :root_path)
		end
		
		Auditor::AuditRecord.create(entry: "#{current_doctor.full_name} fired #{@fired_doctor.full_name} from #{@current_facility.name}.", subject: "DepartmentUpdate", author: current_doctor.full_name)

		flash[:success] = 'Successfully fired!'
		redirect_back(fallback_location: :root_path)
	end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_appointment_card.html.erb
<div class="card mb-2 appointment-card">
  <div class="card-body">
    <h5 class="card-title"><%= appointment.patient.full_name %></h5>
    <p class="card-text">

		<strong>Reason: </strong><span class="appointment-card-reason"><%= appointment.reason %></span>
		<br>

    	<% if appointment.scheduled > DateTime.now %>
            <% appointment_text = "Cancel Appointment" %>
    		<sub>Starts <%= time_ago_in_words(appointment.scheduled) %> from now <span class="appointment-card-datetime">(<%= appointment.scheduled.strftime("%Y-%m-%d at %H:%M:%S") %>)</span></sub>
    	<% else %>
            <% appointment_text = "Remove" %>
    		<sub>Began <%= time_ago_in_words(appointment.scheduled) %> ago <span class="appointment-card-datetime">(<%= appointment.scheduled.strftime("%Y-%m-%d at %H:%M:%S") %>)</span></sub>
    	<% end %>
    </p>

    <% if appointment.doctor == current_doctor %>
        <div class="btn-group justify-content-between btn-block" role="group">
            <a class="btn btn-block btn-primary" href="<%= patient_path(appointment.patient.id) %>">View Patient</a>
            <a class="btn  btn-superuser" href="<%= patient_appointment_cancel_appointment_path(appointment.patient.id, appointment.id) %>"><%= appointment_text %></a>
        </div>
    <% else %>
          <a class="btn btn-block btn-primary" href="<%= patient_path(appointment.patient.id) %>">View Patient</a>
    <% end %>

  </div>
</div>

app/views/doctors/_create_patient_modal.html.erb
<div class="modal fade" id="createPatientModal" tabindex="-1" role="dialog" aria-labelledby="createPatientModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" >Create New Patient</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= bootstrap_form_with(model: Patient.new, url: patients_path, local: true) do |f| %>
    			<%= f.text_field :first_name %>
          <%= f.text_field :last_name %>
      </div>
      <div class="modal-footer">
      	<%= f.submit "Create", :class => "btn btn-superuser" %>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    		<% end %>
      </div>
    </div>
  </div>
</div>

app/views/doctors/_doctor_card.html.erb
<div class="card mb-2 doctor-card">
  <div class="card-body">
    <h5 class="card-title"><%= doctor.full_name %></h5>
    <% 
    if doctor.workplace == nil
    	workplace_dept = "None"
    	workplace_facility = "None"
    else
    	workplace_dept = doctor.workplace.name
    	workplace_facility = doctor.workplace.medical_facility.name
    end
    %>
    <p class="card-text">
    	<strong>Facility: </strong><span class="doctor-facility"><%= workplace_facility %></span>
		<br>
		<strong>Department: </strong><span class="doctor-department"><%= workplace_dept %></span>
    </p>

	<a class="btn btn-primary" href="<%= doctor_path(doctor.id) %>">Show</a>
  </div>
</div>

app/views/doctors/_head_card.html.erb
<div class="card mb-2 head-card">
  <div class="card-body">
    <h5 class="card-title">Head of <%= headname %></h5>
	<a class="btn btn-primary" href="<%= link %>">Show</a>
  </div>
</div>

app/views/doctors/_patient_card.html.erb
<div class="card mb-2 patient-card">
  <div class="card-body">
    <h5 class="card-title"><%= patient.full_name %></h5>

    <% if current_doctor.patients.include?(patient) %>
		<div class="btn-group justify-content-between btn-block" role="group">
		    <a class="btn btn-block btn-primary" href="<%= patient_path(patient.id) %>">Show</a>
		    <button class="btn btn-superuser" type="submit" data-toggle="modal" data-target="#reassignDoctorModal-<%= patient.id %>">Reassign</button>
	    </div>
    <% else %>
		  <a class="btn btn-block btn-primary" href="<%= patient_path(patient.id) %>">Show</a>
  	<% end %>
  </div>
</div>

<%= render partial: "reassign_doctor_modal", locals: {patient: patient} %>

app/views/doctors/_reassign_doctor_modal.html.erb
<div class="modal fade" id="reassignDoctorModal-<%= patient.id %>" tabindex="-1" role="dialog" aria-labelledby="reassignDoctorModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Reassign Doctor for <%= patient.full_name %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      	<%= bootstrap_form_with(model: patient, url: patient_assign_doctor_path(patient.id), local: true) do |f| %>
  			<%= f.collection_select(:doctor_id, Doctor.all, :id, :full_name) %>
      </div>
      <div class="modal-footer">
      		<%= f.submit "Save", :class => "btn btn-superuser" %>
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/doctors/index.html.erb
<h1>Doctors</h1>

<div class="card">
	<div class="card-body">

		<div class="input-group mb-3">
			<div class="input-group-prepend">
				<span class="input-group-text" style="color: #ff000;">Search</span>
			</div>
			<input type="text" id="doctor-searchbox" class="form-control" placeholder="Name or Workplace..." onkeyup="doctorSearch()">
		</div>

		<% @doctors.all.each do |doctor| %>
			<%= render partial: 'doctor_card', locals: {doctor: doctor} %>
		<% end %>

	</div>
</div>

<%= javascript_include_tag "doctor_index" %>

app/views/doctors/show.html.erb
<div class="row">
	<div class="col">
		<h1><%= @this_doctor.full_name %></h1>
	</div>
</div>

<div class="row">

	<!-- Doctor Information -->
	<div class="col-md-12 col-lg-8 mb-3">
		<div class="card mt-3">
			<div class="card-body">
				<h5>Doctor Information</h5>
				<% if @this_doctor.superuser? %>
					<p><strong>SUPERUSER</strong></p>
				<% end %>

				<% 
				    if @this_doctor.workplace == nil
				    	workplace_dept = "None"
				    	workplace_facility = "None"
				    else
				    	workplace_dept = @this_doctor.workplace.name
				    	workplace_facility = @this_doctor.workplace.medical_facility.name
				    end
			    %>
			    <p>
			    	<strong>Facility: </strong><span class="doctor-facility"><%= workplace_facility %></span>
					<br>
					<strong>Department: </strong><span class="doctor-department"><%= workplace_dept %></span>
			    </p>

				<% if @this_doctor.workplace != nil %>
					<a class="btn btn-primary" href="<%= medical_facility_department_path(@this_doctor.workplace.medical_facility.id, @this_doctor.workplace.id) %>">View Workplace</a>
				<% end %>
			</div>
		</div>

		<% if Department.where(department_head: @this_doctor).count > 0 || MedicalFacility.where(facility_head: @this_doctor).count > 0 %>
		<div class="card mt-3">
			<div class="card-body">
				<h5>Administrative Positions</h5>

				<% Department.where(department_head: @this_doctor).each do |department| %>
					<%= render partial:"head_card", locals: {headname: "#{department.name} at #{department.medical_facility.name}", link: medical_facility_department_path(department.medical_facility.id, department.id)} %>
				<% end %>

				<% MedicalFacility.where(facility_head: @this_doctor).each do |facility| %>
					<%= render partial:"head_card", locals: {headname: "#{facility.name}", link: medical_facility_path(facility.id)} %>
				<% end %>
			</div>
		</div>
		<% end %>

	</div>

	<!-- Patients and Appointments -->
	<div class="col-md-12 col-lg-4">

		<!-- Tab Header -->
		<ul id="doctor_tabs" class="nav nav-pills mt-3" role="tablist">
		  <li class="nav-item">
		    <a class="nav-link active" id="appointments-tab" data-toggle="tab" role="tab" aria-controls="appointments" href="#appointments" aria-selected="true">Appointments</a>
		  </li>
		  <li class="nav-item">
		    <a class="nav-link" id="patients-tab" data-toggle="tab" role="tab"  aria-controls="patients" href="#patients" aria-selected="false">Patients</a>
		  </li>
		</ul>

		<!-- Tab Content -->
		<div class="tab-content">

			<!-- Appointments -->
			<div class="tab-pane active" id="appointments" role="tabpanel" aria-labelledby="appointments-tab">
				<div class="card border-flat-top-left">
					<div class="card-body">
						<!-- Appointment Search -->
						<div class="input-group mb-3">
							<div class="input-group-prepend">
								<span class="input-group-text" style="color: #ff000;">Search</span>
							</div>
							<input type="text" id="appointment-searchbox" class="form-control" placeholder="Patient Name, Time or Reason..." onkeyup="appointmentSearch()">
						</div>

						<!-- Appointment List -->
						<ul class="list-group list-group-flush">
							<% @this_doctor.appointments.order('appointments.scheduled ASC').each do |appointment| %>
								<%= render partial:"appointment_card", locals: {appointment: appointment} %>
							<% end %>
							<% if @this_doctor.appointments.empty? %>
								<% if current_doctor == @this_doctor %>
									You have no appointments. Yay!
								<% else %>
									<%= @this_doctor.full_name %> has no appointments.
								<% end %>
							<% end %>
						</ul>
					</div>
				</div>
			</div>

			<!-- Patients -->
			<div class="tab-pane" id="patients" role="tabpanel" aria-labelledby="patients-tab">
				<div class="card border-flat-top-left">
					<div class="card-body">
						<!-- Doctor Controls for creating new patient -->
						<% if current_doctor == @this_doctor %>
							<button class="btn btn-sm btn-block btn-superuser mb-3" type="submit" data-toggle="modal" data-target="#createPatientModal">New Patient</button>
						<% end %>

						<!-- Patient Search -->
						<div class="input-group mb-3">
							<div class="input-group-prepend">
								<span class="input-group-text" style="color: #ff000;">Search</span>
							</div>
							<input type="text" id="patient-searchbox" class="form-control" placeholder="Patient Name..." onkeyup="patientSearch()">
						</div>

						<!-- Patient List -->
						<ul class="list-group list-group-flush">
							<% @this_doctor.patients.each do |patient| %>
								<%= render partial:"patient_card", locals: {patient: patient} %>
							<% end %>
							<% if @this_doctor.patients.empty? %>
								<% if current_doctor == @this_doctor %>
									You have no patients. Yay!
								<% else %>
									<%= @this_doctor.full_name %> has no patients.
								<% end %>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<%= render partial: "create_patient_modal" %>

<%= javascript_include_tag "doctor_show" %>