config/routes.rb
Rails.application.routes.draw do

  # Devise setup
  devise_for :doctors, except: [:show], path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}, :controllers => { registrations: 'registrations' }
  
  # Landing Page / Root route
  get '/', to: 'landing_page#view', as: :root_path

  authenticate :doctor do
    
    # Auditor setup
    mount Auditor::Engine, at: '/', as: 'auditor'

    # Medical Facility routes
    resources :medical_facility, only: [:index, :create, :edit, :update, :show, :destroy], path: '/facilities' do
    	get :remove_facility_head
    	post :assign_facility_head
    	post :search_doctors

      resources :department, only: [:create, :show] do
        get :remove_department_head
        post :assign_department_head
        post :hire

        resources :referrals, only: [:create]

        resources :doctors, only: [] do
          get :fire
        end
      end
    end

    # Doctor routes
    resources :doctors, only: [:index, :show]

    # Patient routes
    resources :patients, only: [:index, :show, :create, :update] do
      patch :assign_doctor
      post :create_appointment
      post :create_appointment_from_referral

      resources :patient_records, only: [:create] do
        patch :archive_record
      end

      resources :appointments, only: [] do
        get :cancel_appointment
      end
    end

  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZEAL Healthcare</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  </head>

  <body style="background: url(<%= asset_path('background_bright_squares.png') %>">
  	<!-- Navigation Bar -->
	<nav class="navbar navbar-expand-lg bg-secondary fixed-top mb-3">
		<div class="container">
			<!-- ZEAL Logo -->
			<a class="navbar-brand" href="<%= doctor_path(current_doctor.id) %>">
				<img src=<%= asset_path('logo_nosub.png') %> height="30" alt="">
			</a>

			<!-- Hamburger Icon -->
			<button class="ml-auto navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
				<span class="navbar-toggler-icon"></span>
			</button>

			<!-- The rest of the Navbar -->
			<div class="collapse navbar-collapse" id="navbarSupportedContent">

		        <ul class="navbar-nav ml-auto">
		            <li class="nav-item">
		                <a class="nav-link" href="<%= doctor_path(current_doctor.id) %>"><%= current_doctor.first_name.possessive %> Page</a>
		            </li>
		            <li class="nav-item">
		                <a class="nav-link" href="<%= doctors_path %>">Doctors</a>
		            </li>
		            <li class="nav-item">
		                <a class="nav-link" href="<%= patients_path %>">Patients</a>
		            </li>
		            <li class="nav-item">
		                <a class="nav-link" href="<%= medical_facility_index_path %>">Facilities</a>
		            </li>
		            <% if current_doctor.superuser? %>
						<li class="nav-item">
							<a class="nav-link" href="<%= auditor.audits_path %>">Auditor</a>
						</li>
					<% end %>
		            <li class="nav-item">
		                <a class="nav-link" href="<%= destroy_doctor_session_path %>">Logout</a>
		            </li>
		        </ul>
		    </div>
		</div>
	</nav>
  	
  	<!-- Body content -->
  	<div data-turbolinks=false class="container mb-3">
  		
  		<!-- Padding for header -->
  		<div class="row pt-5 pb-4"></div>

		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>">
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				<%= value %>
			</div>
		<% end %>

	    <%= yield %>
	    
	    <!-- Padding for footer -->
	    <div class="row pt-3 pb-3"></div>
  	</div>

  	<!-- Footer -->
  	<footer class="bg-secondary fixed-bottom">
  		<div class="container">
  			<a class="nav-link" href="https://twitter.com/TheReccy">Copyright 2018 - Aaron Meaney</a>
  		</div>
  	</footer>
  </body>
</html>

app/views/layouts/landing_page.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Welcome to ZEAL</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'landing_page', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'landing_page', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  </head>

  <body>
    <div class="overlay"></div>

    <div class="masthead" data-turbolinks="false">
      <div class="masthead-bg"></div>
      <div class="container h-100">
        <div class="row h-100">
          <div class="col-12 my-auto">
            <div class="masthead-content text-white py-5 py-md-0">
              <%= link_to image_tag("logo_full.png", :class => "img-fluid"), "/" %>
              <div class="row"><br></div>
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>